### ISSUE TITLE
CEC scp file transfer limit

### ISSUE THREAD

**Issue by DeyTong** [pydio/cells-client#10]
Using Cells Client v4.0.0, I noticed that there is limit of 100 files when transferring files regardless of the file size.

**Versions used:**
Pydio Cells Home Edition 4.1.0
Cells Client version 4.0.0

**What is the server OS? Database name/version? Browser name or mobile device description (if issue appears client-side)?**
Server: Ubuntu 20.04
Client(s): Ubuntu 20.04, Zorin 16.2

**What steps have you taken to resolve this issue already?**
CEC versions 2.2.0 and 4.0.0 were tested on two different instances of Pydio Cells Server. Both were limited to 100 files when transferring files using ./cec scp.

Sample output:

`
user@user:~/Downloads$ ./cec ls images | wc -l
`
`181
`
`user@user:~/Downloads$ ./cec scp cells://images ./images`
`
Downloading cells://images to ./images
100% [====================================================================] Transferred 100/100 files and folders (6s)
`

**Comment by bsinou** [comment]
Thanks for reporting.
Indeed, the handling of pagination when collecting the remote files to download had been forgotten.
Thus, we only got the first 100 items from large folders.

It is now fixed in main branch and will be included in the next 4.1.0 release.

You might already try with latest dev build [from our download server](https://download.pydio.com/pub/cells-client/dev/)  

Feedback are welcome!

**Comment by bsinou** [comment]
If you want to test that this is now fixed, now could be a good moment:
We have released an alpha version that we will test intensively, but if you have some feedback, they are welcome:

The alpha 2 is fresh out of our CICD pipe and can be downloaded [from our DL server](https://download.pydio.com/pub/cells-client/release/4.1.0-alpha2)

**Comment by bsinou** [comment]
Release v4.1.0 fixes this, see: https://github.com/pydio/cells-client/releases/tag/v4.1.0

Closing the issue.
Let us know if you encounter any new one! (hopefully not too soon ;) )
