### ISSUE TITLE
Generic API endpoints support

### ISSUE THREAD

**Issue by drzraf** [pydio/cells-client#4]
As I understand now `cells-client` is a command-line tool to interact with **files/users related features of Pydio** only.
Don't you think that (maybe using swagger code generator?), it'd be possible for this tool to be a also become a versatile **API client** (supporting all swagger-defined endpoints of cells)?

**Comment by bsinou** [comment]
We have no plan to implement the full REST API in the Cells Client, we rather add new features when requested or necessary.

Yet, the Cells Client relies on the [Cells SDK for go](https://github.com/pydio/cells-sdk-go/tree/master/v2) that is indeed generated from swagger and only add some convenience methods to easily handle authentication processes.
=> in the SDK, all REST endpoints are exposed as easily usable objects, and you can explore the Cells Client (this repo)'s code to find some valuable example.

It is also worth noting that we also generate the SDK for Java and Javascript using swagger. Let us know if it might prove useful for you it will give some incentive to finalize their publication (it is some work in process in the background with low priority as we speek)

**Comment by cdujeu** [comment]
Closing (staled)
