### ISSUE TITLE
Cec client 2.0.5 not compatible with Cells 2.2.0-rc2

### ISSUE THREAD

**Issue by firmero** [pydio/cells-client#5]
Cannot get working together. Client is probably not up to date with server api.

Server side:
```
ERROR        pydio.rest.meta        Rest Error 500        {"error": "unknown field \"NodeUuids\" in rest.GetBulkMetaRequest"}
```
Client side:
```
could not list files at , cause: unknown error (status 500): {}
```

Probably caused by changing [cells/common/proto/rest/data.proto](https://github.com/pydio/cells/blob/v2.2.0-rc2/common/proto/rest/data.proto#L50) by this [commit](https://github.com/pydio/cells/commit/5d3533f589b2b1ae60e57a870572067eb3ed4771).

**Comment by cdujeu** [comment]
Indeed, we have to bump the SDK version. 
thanks for pointing out.

**Comment by firmero** [comment]
Thanks, now cec v2.0.6 works with cell v2.2.0-rc2. It's nice to have such a utility.
