### ISSUE TITLE
ubuntu Linux gnome-keyring/

### ISSUE THREAD

**Issue by GwynethLlewelyn** [pydio/cells-client#7]
Hello there,

I've just installed commit [52518a9](https://github.com/pydio/cells-client/commit/52518a9d46ba263f5dfb0c73e9c66a2bd6cb1e3d), compiled with go 1.19.2 under Ubuntu Linux 22.04.1 LTS (jammy) on the x86_64 architecture.

When launching `cells-client`, the following error is thrown:

    2022/10/14 17:33:07 unexpected error during initialisation phase: exec: "dbus-launch": executable file not found in $PATH

This is mostly because under Pydio 4.0.0 RC7, Cells now uses the underlying keyring (under Ubuntu Linux, it's usually `gnome-keyring`, even if you don't actually _use_ GNOME...), and I didn't have it properly installed.

Under Debian/Ubuntu Linux, this is easily accomplished with something like:

```sh
$ sudo apt install dbus-launch libpam-gnome-keyring gnome-keyring-pkcs11
```

(The line above should be on a README somewhere!)

After that, you can safely launch `cells-client config add` and everything should work again.

Note: macOS and Windows (and possibly some other OSes) have their own native keyring systems installed by default, so they will not get this error; it's only on Linux configured as a server (which means that no GUI is installed) that you might get this error and require the necessary components for manage a keyring.

**Comment by bsinou** [comment]
Thanks for reporting. 
I'm working a v2.2.2 release that updates a few TPs and add a missing flag to test versions and would be glad to add this in the ReadMe if it helps others.

Could you just please help me with a small tip: which OS could I install on a VM to make a quick test of the issue and the fix?

Thanks.
